name: Main Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  buildpush:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform: [linux/arm]

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERNAME }}
        password: ${{ secrets.DOCKERKEY }}

    - name: Build Docker image for development
      run: docker build --platform linux/arm/v6 --target development . --tag ${{ secrets.DOCKERNAME }}/flask-mio:dev

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKERNAME }}/flask-mio:dev
