name: Main Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:

  buildpush:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERNAME }}
        password: ${{ secrets.DOCKERKEY }}

    - name: Build Docker image for development
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/arm/v6 --no-cache --push --target development . --tag ${{ secrets.DOCKERNAME }}/flask-mio:dev
